version: '2'
services:
  db:
    image: antpolis/mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  web:
    depends_on:
      - db
    image: antpolis/base-php-machine
    links:
      - db:db
    ports:
      - "80:80"
    restart: always
    volumes:
      - './:/var/www/html'